name: Premerge check
run-name: ${{ github.actor }} run premerge check

on:
    pull_request:
        branches:
            - master
    push:
        branches: [master]

jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v3

            - name: Staring Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-version}}

            - name: install modules
              run: npm install

            - name: run build
              run: npm run build

            - name: lint code
              run: npm run lint

            - name: run typeckeck
              run: npm run type-check
